language: php
sudo: false
php:
- 5.3
- 5.4
- 5.5
- 5.6
- 7.0
matrix:
  allow_failures:
  - php: 5.3
  - php: 5.4
  - php: 5.6
  - php: 7.0
env:
  matrix:
  - MAGENTO_VERSION=magento-ce-1.9.2.2
  - MAGENTO_VERSION=magento-ce-1.9.2.1
  - MAGENTO_VERSION=magento-ce-1.9.2.0
  - MAGENTO_VERSION=magento-ce-1.9.1.1
  - MAGENTO_VERSION=magento-mirror-1.8.1.0
  - MAGENTO_VERSION=magento-mirror-1.7.0.2
  - MAGENTO_VERSION=magento-mirror-1.6.2.0
  global:
  - secure: YD4LBUDzWq8gAcfGhpyEMhvbfuw5BPrnyVTV+KclKUQOWtYY1OtuTnzdhCE+N/dEMEFB1TWVKSN1wXD8NHSXCDy1MTytB4+SFY8jEjYhW4hzMwyPEhVqSn+gxmFywcvzsbiVZKxU0F1FisrYT+uvcjm6Slfrmsy8Vjd0OsbldQc=
  - secure: MiWZyk+O3O1cu8N0sEVA6c5paMVGgrw90As8eFkueqZoNfLqBA8HpP7d1AHky1EACyZipBav8SbM4ftV2tQVJKrl0cVXspqGI3d8DJjvyqlEYDDJwTyy/gMKYX9Y55MhYUAc7ZlwywdhgylCmLIxUGMsU8oXDUCSg9CnODswEBQ=
  - secure: VODOGsZQI8XcSek40K1HLWADIlmEXrQaswP9DUcjRbsBaHUgzv2Rvg+qYif4wQKARf5l7mNgY9P7yWjs9mAtxVN9kaV2gaCmR6V0k1etPxztA6zJoLE8hHHmm+xVcJTCv1aLsnm2EbYiSIwiWIDWMFxAtaLU5uhf03hKm/vRmdg=
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/setup.sh
  | bash
notifications:
  slack:
    secure: mfQXhgIJSeRwMdRpTE4kT99rwGEPZt/15d6gi8HXcamNchcoWQ5dQ04NxuYrWG8z8IpFmrXi1dCoQrP+oPHpQZzF6b2+IE7Eo0JMP8X9/j7VLrn/NKCS2QRYgR5psHbEICx0/ObCFXwHLB+cEAzvbMsArQVYdM15qQFOAl/ijhg=
