language: php
sudo: false
php:
- 5.3
- 5.4
- 5.5
- 5.6
- 7.0
matrix:
  allow_failures:
  - php: 5.3
  - php: 5.4
  - php: 5.6
  - php: 7.0
env:
  matrix:
  - MAGENTO_VERSION=magento-ce-1.9.2.2
  - MAGENTO_VERSION=magento-ce-1.9.2.1
  - MAGENTO_VERSION=magento-ce-1.9.2.0
  - MAGENTO_VERSION=magento-mirror-1.8.1.0
  - MAGENTO_VERSION=magento-mirror-1.7.0.2
  - MAGENTO_VERSION=magento-mirror-1.6.2.0
  global:
  - secure: k+X0QiEHoaT8mLoAkfu11NfmR3UzwWNKdXyT4i5OPqVmS4kqkFkBGUqDTEMUQIwWNbiVCGh3eqpqYAds+YCKJwbjXwdwJTa05bc+Bz5DHaNUOkpUQ9CuR/+qYjLpBz6kgf7a/W7UX1WiRP6RIQaEvaVXJUSgYLsQrGLfTg7AH7k=
  - secure: ACtpRDkKOoceH5Na+qsxcpJrbFS1DxqlWoQ/qUeBwSONIlAe4RCnsxQnit+uyys98w5UzogVw7rm2b866fXcUeo4s0agfgJXNuiIk8wq0Ub1MnAQpG9z8rq2n7rhqgVnYVPRnS9NKkq/GauaIn54KesMxyqSJZRJ+ehQdCcftXk=
  - secure: Hkvbn7maeJ/D0OHOG8neqT8KChSaQWo4yJDuAfQSPdKqvjsT9NmQCqhFApXSfjZr3B0TZ07EmwIK6ka70MZRj3/jBcnZOHMLOwKPWLCnL1EwukM6a0Px/I0xOnraM7ri4PvFxS1xDN47x/6sypRnpsRo9f6e7bq45xfwTs/Ps5w=
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/setup.sh
  | bash
notifications:
  slack:
    secure: m9X8fowtqS/fLGV8+31QCTuCAuaQe9HllVRicRxwz+kDh2My5d/VT5CWq8dF5hsyzcPV165OtKRbR8ulk+qapLBxLC30V+EZTuKPmxZLPsGvSVkvbcp8PsbkYj2t4AV3iyk4OqSAA4jrF1TWxbUWPFDmSeuI8mTDNGR85BT4eRM=
